### ISSUE TITLE
[Tracking]: W3C Compliance

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1205]
The W3C Draft contains a couple of changes we'd need to make to be compliant. Now that it seems things are starting to stay stable and the W3C DTCG asked tool vendors to implement this draft, we should do that!

```[tasklist]
### Definition of Done
- [ ] https://github.com/six7/figma-tokens/issues/999
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2052
- [x] https://github.com/six7/figma-tokens/issues/587
- [x] https://github.com/six7/figma-tokens/issues/1201
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1747
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1811
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1845
```

```[tasklist]
### Nice to have
- [x] https://github.com/six7/figma-tokens/issues/1266
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1748
- [ ] https://github.com/six7/figma-tokens/issues/299
- [ ] https://github.com/six7/figma-tokens/issues/1295
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1199
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1746
```

### 🔴 Blocked due to spec still in progress
- [ ] <https://github.com/six7/figma-tokens/issues/1199>

**Comment by bseiler-nca** [comment]
@six7 $description can be also an element within a group
https://design-tokens.github.io/community-group/format/#description-0

is this also done with this task or should I open a new one?

**Comment by six7** [comment]
Marking as done, will be part of 2.0
