### ISSUE TITLE
[Epic] Composition Tokens: M2

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#1217]
Composition tokens was launched with the 102 release, we should plan for the next iteration of this feature.

```[tasklist]
### Tasks for M2
- [x] https://github.com/six7/figma-tokens/issues/1185
- [ ] https://github.com/six7/figma-tokens/issues/1093
- [ ] https://github.com/six7/figma-tokens/issues/1085
- [x] https://github.com/six7/figma-tokens/issues/1065
- [ ] https://github.com/six7/figma-tokens/issues/1218
- [ ] https://github.com/six7/figma-tokens/issues/1219
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1424
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1682
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1614
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2124
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2335
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1943
```

If you've used composition tokens and have any feedback for us, leave your feedback in this issue 🙏

**Comment by engegu** [comment]
We are trying this out as an alternative to component tokens, a major hindrance is the inspect experience. It needs to be brought in line with other tokens in that there is at least a mouseover that lists referenced tokens and values.

**Comment by eekprice** [comment]
**Composition request**: it would be great to be able to reference compositions within compositions.

**Why**: I’ve created a collection of what I call velocity tokens - which are groups of tokens that make up almost all of my components. It would be great to create another set of component compositions that utilize the velocity tokens, making it a lot quicker to build inside of studio.

**Another request for creating compositions**:
It would wonderful to automate the composition creating process.

**Recommendation**: After applying all your tokens to a frame in figma, select the frame. We already know what tokens are applied in that frame with the inspect tab. It could be cool to have a button that said “create composition” and it would pull all those tokens into a new composition with the name being blank.

**Comment by vnys** [comment]
## Composing composition tokens

Here’s what I’d like to see for composition tokens: If we could _compose_ composition tokens, we could create base shapes or colour sets that could be reused across components. Similarly to how inheritance works with CSS, I would expect that if two composition tokens has conflicting values, the last one wins. But if you want to _override_ a value, the order doesn’t matter because a property that you create directly on a composition token such as fontWeight for `<Button>` in the following example, has higher specificity than a value from another composition token that you pull in. 

```mermaid
classDiagram
    note for colorset_action_primary "Colour “molecule” consisting of \n colours for bg, text, border, icon"
    Button *-- spacing_insetSquish_md : Composition
    Tab *-- spacing_insetSquish_md : Composition
    Button *-- typography_sm : Composition
    Tab *-- typography_md : Composition
    Button *-- colorset_primary : Composition
    Tab *-- colorset_primary_inverse : Composition
    
    
    class spacing_insetSquish_md {
        verticalSpace_sm  
        horisontalSpace_md
    }
    
    class typography_md {
        fontSize_md
        lineHeight_md
        fontWeight_400
    }
    
    class typography_sm {
        fontSize_sm
        lineHeight_sm
        fontWeight_400
    }
    
    class Button {
        fontWeight_500
        action()
    }
    
    class Tab {
        navigation()
    }
    
    class colorset_primary {
        bgColor_blue700
        textColor_neutral100
        borderColor_blue900
    }
    
    class colorset_primary_inverse {
        bgColor_blue100
        textColor_blue900
        borderColor_blue700
    }
        
```

**Comment by six7** [comment]
Thanks @vnys - i've used your input in the issue's description for applying more than 1 composition token: https://github.com/tokens-studio/figma-plugin/issues/1682

**Comment by SamIam4Hyma** [comment]
closing this epic as all sub-issues have been closed or migrated into Featurebase. 

[🪙 ➕ Support multiple tokens per layer of the same type](https://tokensstudio.featurebase.app/p/multiple-token-per-layer)
