### ISSUE TITLE
[Epic]: Motion-related tokens

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1749]
Let's work on all motion-related tokens as one epic given they're interconnected.

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/299
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1748
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1295
```

**Comment by RobbyUitbeijerse** [comment]
Hey @six7, we would love to use these types of tokens in our project. Is there any ETA on this feature?

**Comment by SimonLeclercq** [comment]
Hey folks, do you have any visibility on this topic? We're in great need of this kind of element 🙏 If you need anyfeedback, feel free to ask!

**Comment by kaytran12** [comment]
Our team would love to have motion tokens as well
