### ISSUE TITLE
[Epic]: Performance improvements

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1903]
Let's focus on some performance improvements.

Three main areas:
- Improve stability of the plugin
- Improve efficiency of how we handle large documents
- Improve efficiency when it comes to internal tokens, their sets and the logic around resolving

```[tasklist]
- [ ] #1755
- [ ] #1899
- [ ] #1901
- [ ] #1902
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1751
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1906
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1900
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1957
```

**Comment by SorsOps** [comment]
@six7 I think the other crucial task for this is to add performance profiling within the plugin so that we can track these expensive operations 

The `resolveTokenValues` and any interactions on the plugin side where the most expensive transactionslike walking the document should be wrapped with a Sentry transaction so we can proactively detect these bottlenecks in performance

**Comment by six7** [comment]
Closing, this was done
