### ISSUE TITLE
[Epic]: Variables M2

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2106]
With basic support for Figma's variables out, let's use this issue as a collection of things we want to work on for a M2 of the feature.
```[tasklist]
### Tasks
- [x] Perform user research on what features are missing the most
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2211
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2081
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2023
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2008
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1999
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2186
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2187
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2120
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1969
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2193
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2194
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2233
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2215
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2213
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2067
```

**Comment by six7** [comment]
Closing in favor of https://github.com/tokens-studio/figma-plugin/issues/2489
