### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2469]
Currently some of the error messages in the plugin are not super clear and could be improved. 

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2357
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2487
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2609
```

**Comment by six7** [comment]
Closing in favor of tackling the smaller issues
