### ISSUE TITLE
[Epic]: Plugin 2.0

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2489]
```[tasklist]
### W3C specs support
- [ ] https://github.com/tokens-studio/figma-plugin/issues/999
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1811
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1747
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2052
```

```[tasklist]
### Variables M2
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2406
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1969
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1974
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2411
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2412
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2443
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2023
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2120
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2211
```

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/pull/2467
- [ ] https://github.com/tokens-studio/figma-plugin/pull/2473
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1855
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2393
- [ ] https://github.com/tokens-studio/figma-plugin/pull/2484
```

**Comment by SamIam4Hyma** [comment]
@six7 can we close this epic now that the release is done?

**Comment by SamIam4Hyma** [comment]
@six7 This release has passed. Can we close?
