### ISSUE TITLE
[Epic]:Plugin 2.1

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2492]
In this epic we are going to focus on improving the viewing experience of design tokens in the plugin. To do so we are focusing on 3 major areas:
- Proper feedback on actions allowing users to understand errors and highlighting ways to take corrective action
- Improve the way tokens are viewed 
- Prepare for future epic
```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2469
```

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1024
- [ ] https://github.com/tokens-studio/figma-plugin/issues/650
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1741
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1621
```

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2458
```

**Comment by six7** [comment]
@esthercheran can you describe this epic a bit? We have some context in the Figjam, let's have it here too.

Let's treat these like proper epics with a proper description and product shaping
