### ISSUE TITLE
2.1: Token Viewing experience

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2678]
With this release we want to invest in the token viewing experience:

- Schema driven token editing
- Ability to define and change token type
- Token scoping for variables
- Parametric UI
- All sets token view
- Split view token views
- Sibling sets
- Token set descriptions
- Token group descriptions
- Token filters
- Single token visualization flow
- Rearrange token groups

```[tasklist]
### Design issues
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/1
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/2
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/3
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/4
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/5
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/6
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/7
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/8
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/9
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/10
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/11
- [ ] https://github.com/tokens-studio/figma-plugin-design/issues/12
```

```[tasklist]
### Preparations for 2.2 (we could move this into 2.2 as well if this epic is too big)
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2458
```

```[tasklist]
- [ ] https://github.com/tokens-studio/figma-plugin/issues/650 (this is a prereq for 1024)
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1024
```

**Comment by SamIam4Hyma** [comment]
@six7 Here's a list of current posts in featurebase related to this epic for your consideration. 

I want to highlight the Token Organization topic as it has the highest number of tickets migrated from Github and it was a top requested topic when we did the last user survey. 

- [🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
- [📏 Expand accepted reference token types and units](https://tokensstudio.featurebase.app/p/expand-accepted-reference-token-types)
- [💡 Add support for scoping and publishing variables and styles](https://tokensstudio.featurebase.app/p/add-support-for-scoping-and-publishing-variables-and-styles)
- [💡Removing a token removes the design property in figma](https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma)
- [💡 🪙 Token metadata enhancements](https://tokensstudio.featurebase.app/p/token-metadata-enhancements)
- [❇️ DTCG W3C | Token Group Metadata - Description and Type](https://tokensstudio.featurebase.app/p/token-group-metadata-description-and-type)
- [🪙 Add support for Token usage metadata](https://tokensstudio.featurebase.app/p/token-usage-metadata)
- [🪙 ➕ Apply token workflow enhancements](https://tokensstudio.featurebase.app/p/apply-token-workflow-enhancements)

**Comment by SamIam4Hyma** [comment]
This epic can be closed as all these items are in featurebase and this work isn't actively planned. It will be shaped in a different way.
